# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WCStoreApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WCStoreApp
  pod 'shared', :path => '../shared'
  pod 'KMPNativeCoroutinesCombine', '0.12.2'
  pod 'NavigationStack'
  pod 'SystemNotification'

end
