[versions]
kotlin = "1.5.21"
compose = "1.0.1"
hilt = "2.38.1"
room = "2.3.0"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
androidx-core = "androidx.core:core-ktx:1.6.0"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.1"
lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1"
lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:1.0.0-alpha07"
material = "com.google.android.material:material:1.4.0"
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-uipreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-uitooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose"}
compose-activity = "androidx.activity:activity-compose:1.3.1"
compose-constraintLayout = "androidx.constraintlayout:constraintlayout-compose:1.0.0-beta02"
accompanist-insets-ui = "com.google.accompanist:accompanist-insets-ui:0.18.0"
accompanist-pager = "com.google.accompanist:accompanist-pager:0.18.0"
coil-compose = "io.coil-kt:coil-compose:1.3.2"
hilt-android = { module =  "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module =  "com.google.dagger:hilt-compiler", version.ref = "hilt" }
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2"
retrofit = "com.squareup.retrofit2:retrofit:2.9.0"
retrofit-kotlinx-serialization-converter = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.8.0"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2"
paging-runtime = "androidx.paging:paging-runtime:3.0.1"
paging-compose = "androidx.paging:paging-compose:1.0.0-alpha12"
okhttp-signpost = "se.akerfeldt:okhttp-signpost:1.1.0"

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room"}
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room"}
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

navigation-compose = "androidx.navigation:navigation-compose:2.4.0-alpha09"
hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.0.0-alpha03"

font-tabler-icons = "br.com.devsrsouza.compose.icons.android:tabler-icons:1.0.0"

junit = "junit:junit:4.+"
androidx-test = "androidx.test.ext:junit:1.1.3"
androidx-espresso = "androidx.test.espresso:espresso-core:3.4.0"
compose-uitest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

[bundles]
compose = ["compose-ui", "compose-material", "compose-uipreview", "compose-activity", "compose-constraintLayout"]
paging = ["paging-runtime", "paging-compose"]
room = ["room-runtime", "room-ktx"]

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
